import "./globals.css";
import MyHeader from "@/components/header";
import MyFooter from "@/components/footer";



export const metadata = {
  title: "Next App With Headless Wordpress",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full bg-[url(/images/bg2.jpg)]  bg-no-repeat bg-cover bg-top bg-fixed">

        <div className="max-w-[780px] bg-white min-h-screen mx-auto p-4">
          <MyHeader />
          {children}
          <MyFooter />
        </div>

      </body>
    </html>
  );
}
